import type { FastifyInstance } from 'fastify';
import { registerAiRoutes } from './ai.routes.js';
import { registerAuditRoutes } from './audit.routes.js';
import { registerAuthRoutes } from './auth.routes.js';
import { registerCalendarRoutes } from './calendar.routes.js';
import { registerLiveRoutes } from './live.routes.js';
import { registerCmsRoutes } from './cms.routes.js';
import { registerEntitlementsRoutes } from './entitlements.routes.js';
import { registerHealthRoutes } from './health.routes.js';
import { registerInstallRoutes } from './install.routes.js';
import { registerPagesRoutes } from './pages.routes.js';
import { registerPaymentsRoutes } from './payments.routes.js';
import { registerPublicDocsRoutes } from './publicDocs.routes.js';
import { registerUsageRoutes } from './usage.routes.js';

export const registerRoutes = (app: FastifyInstance): void => {
  registerHealthRoutes(app);
  registerPublicDocsRoutes(app);
  registerPagesRoutes(app);
  registerInstallRoutes(app);
  registerAuthRoutes(app);
  registerEntitlementsRoutes(app);
  registerUsageRoutes(app);
  registerAuditRoutes(app);
  registerCmsRoutes(app);
  registerCalendarRoutes(app);
  registerLiveRoutes(app);
  registerPaymentsRoutes(app);
  registerAiRoutes(app);
};
