export const API = {
  HEALTH: '/api/health',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_REGISTER: '/api/auth/register',
  AUTH_ME: '/api/auth/me',
  AUTH_GOOGLE: '/api/auth/google',
  AUTH_GITHUB: '/api/auth/github',
  AUTH_GOOGLE_CALLBACK: '/api/auth/google/callback',
  AUTH_GITHUB_CALLBACK: '/api/auth/github/callback',
  ENTITLEMENTS: '/api/entitlements',
  USAGE: '/api/usage',
  AUDIT_LOGS: '/api/audit-logs',
  PAYMENTS_AI: '/api/payments/ai/advise',
  AI_COMPLETE: '/api/ai/complete',
  CMS_DASHBOARD: '/api/cms/dashboard',
  CMS_PAGES: '/api/cms/pages',
  CMS_PAGE: '/api/cms/pages/:id',
  CMS_CONTENT: '/api/cms/content',
  CMS_CONTENT_COLLECTION: '/api/cms/content/:collection',
  CMS_MEDIA: '/api/cms/media',
  CMS_MEDIA_SIGN: '/api/cms/media/sign',
  CMS_PLANS: '/api/cms/plans',
  PUBLIC_DOCS: '/api/public/docs',
  PUBLIC_DOCS_SLUG: '/api/public/docs/:slug',
} as const;
